### ISSUE TITLE
귱굼증!! 및 로고

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#1]
@Woohwahwa 

![image](https://user-images.githubusercontent.com/28642484/101274552-6f0a1380-37e2-11eb-88e7-440ed15e3a32.png)

최근 커밋으로 실행해보니 오류가 나오네요~~~ 어떻게 해야 작업한것을 구경할수 있을까요?!?!

이전 커밋의 favicon에 남송리 삼번지가 있네요!

페이지 시작로고 (지금은 Hello)에 사용할 로고를 올립니다!
뒷 배경이 투명인 PNG로 필요할까요?

![image](https://user-images.githubusercontent.com/28642484/101274655-53533d00-37e3-11eb-8133-4442f43174f0.png)

![image](https://user-images.githubusercontent.com/28642484/101274742-e2605500-37e3-11eb-8f0d-f63d4d9dda22.png)

**Comment by Woohwahwa** [comment]
고마워요!! 실행은 npm install을 한번 해주면 될 것 같아요! 상태 관리를 위해 추가한 라이브러리를 설치해주어야 한답니당!

**Comment by KoEonYack** [comment]
@Woohwahwa 
npm i를 했는데 뭔가 버전이 안맞는 부분이 있나보네요 (퐁퐁..,,,)

**Comment by Woohwahwa** [comment]
오잉...! 제가 내일 봐줄게요....!! @KoEonYack

**Comment by KoEonYack** [comment]
@Woohwahwa 
윈도 놋북이라 ! 들고갈일이 생기면 살펴보아요 : )

**Comment by Woohwahwa** [comment]
@KoEonYack 아항! 좋아요!!
