### ISSUE TITLE
gh-page배포했어요~

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#10]
@leedoopal  안녕하세요~

제 개발 환경에서 `npm run deploy`하니깐 바로 배포되네요!

-------------

<img width="1252" alt="스크린샷 2021-03-29 오후 10 29 28" src="https://user-images.githubusercontent.com/28642484/112844030-3a4a0100-90de-11eb-85d1-933de470621c.png">

-------------

gh-pages branch에 Updates올라가면 Publish에 성공한 것이니 확인해보세요!!
Dev Event Client 페이지 내 행사 검색이 순식간에 솩솩 되는게 신기하네요!!
빨리 서버를 만들어봐야겠어요!!

**Comment by leedoopal** [comment]
@KoEonYack 답이 너무 늦었네요!;; 서버 관련 모델이 대략 생긴다면 말해주어요~~
