### ISSUE TITLE
[💡 개선 아이디어] 회원관리 패이지 개선

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#102]
@leedoopal 

선생님 반가워요~~~~~~! 목은 괜찮나요~~~?!😢

탕탕특공대🔫 이틀만에 무과금으로 3챕터까지 깻어요~~~~ 아직까진 무과금으로 수월해요!!!

-----------

## 관리자 -> 회원 관리 리스트 영역

![image](https://user-images.githubusercontent.com/28642484/194883521-3bd0cf6c-44ab-4782-aded-252c72ba647a.png)

(1) 아이디가 아니라, 이메일을 표시하고 있어요!!! 공간이 많아서 아이디, 이메일 다 표시해도 좋을것 같아요!
(2) API 호출해보면 user_no라는 필드가 추가로 내려올꺼에요!, 회원번호인데요! (JWT의 Payload의 user_no값과 같은 값이에요!) 해당 같이 (2) 영역, 표 제일 앞부분에 추가 되었으면 좋겠어요!!

**Comment by leedoopal** [comment]
@KoEonYack 
무과금으로 3챕터요..??!! 대단해요~~~~~~~~~~~~~~~~~~~~
소질이 있나봐요~~~~~~

선생님 말해준거 추가해서 dev, prod 배포 했어요!

**Comment by KoEonYack** [comment]
@leedoopal 

배포된거 확인했어요~~!!!!

바쁠텐데 로켓 개발 고마워요~~~~~~!! 🚀
