### ISSUE TITLE
달력view.제안~

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#11]
<img width="1429" alt="스크린샷 2021-03-29 오후 11 03 41" src="https://user-images.githubusercontent.com/28642484/112848395-01605b00-90e3-11eb-93c1-3f9e267b33d4.png">

[어썸데브블로그](https://awesome-devblog.netlify.app/korean/teams/events)의  개발자 행사 달력뷰인데요!!

달력뷰를 제안해보아요~

dev event는 현재 선형적 텍스트에서 타일형, 달력뷰까지 제공한다면 근사할꺼에요~~

달력뷰를 예전에 html, css로만  만들어본적 있는데  생각보다 상당히 까다롭더라고요!!

시간 괜찮을때 고려해보세요~~~~~!! 

확인하고 issue 닫아주시면 됩니다!!

**Comment by leedoopal** [comment]
와우 제가 5월의 이슈를 이제 보았네요! 다음 버전(v0.2)에 추가할 수 있도록 할게요~! 좋은 의견 고마워요!
