### ISSUE TITLE
[💡 개선 아이디어] 커버 이미지 사이즈 조정

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#121]
@leedoopal 

선생님 반가워요~~~!!

어제 제안 준것처럼 조정하고~~  이 이슈 닫으면 되어요!! 

어느정도로 조정했는지 알려주세요!! 😀

**Comment by leedoopal** [comment]
퀄리티는 0.9 -> 1로 올리고, 이미지 max-width 도 560 -> 1024로 좀 늘렸어요!

---
근데 저만 그런건지 dev에서는 반영이 안된 것 같고 prod만 되는 것 같은데 나중에 한번 봐줄수있나요?
오늘 배포하려니 뭔가 이상하네요;;

**Comment by KoEonYack** [comment]
@leedoopal 

선생님~~ 개선해주어서 고마워요요!!

<img width="706" alt="스크린샷 2022-12-15 오후 7 22 55" src="https://user-images.githubusercontent.com/28642484/207834764-53383ab4-8750-42a2-aca2-09d60c77f265.png">

스샷 상단이 개발, 하단이 리얼인데 개발이 확실히 화질도 떨어져보이고, 픽셀값도 안보이네요!!
