### ISSUE TITLE
[💡 개선 아이디어] 이벤트 생성 버튼 floating 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#122]
@leedoopal 

반가워요~~~~~!! 오랜만에 제안을 들고왔어요! 

하나도 급한게 아니니 좋은 제안이라고 생각이 든다면 시간이 남을때 하면 되겟어요 !! 

<hr />

<img width="1098" alt="스크린샷 2022-11-26 오후 5 18 48" src="https://user-images.githubusercontent.com/28642484/204079437-45c3ff0a-7e45-44e9-8dfd-39df92431bcf.png">

관리자 페이지에서 행사 버튼이 하단에 있어서 스크롤을 해서 버튼을 눌러야하는데요~

버튼이 하단에 둥실둥실 떠있게 floating 속성을 추가하는게 어떨까요~~?! 그렇다면 스크롤을 내리지 않고 행사 추가 버튼을 누를 수 있겠어요!

**Comment by leedoopal** [comment]
아이디어 주어서 고마워요~! 반영했답니다!
