### ISSUE TITLE
[💡 개선 아이디어] 행사 추가시 종료일자 이동

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#123]
@leedoopal 

이것도 마음에 드는 제안일까요~~~?! 👀 선생님도 같은 불편함을 느끼었을지 모르겠네요!!

<hr />

<img width="386" alt="스크린샷 2022-11-26 오후 5 21 23" src="https://user-images.githubusercontent.com/28642484/204079524-bd261337-bd04-41bd-b231-b0bb89283775.png">

시작 일자를 선택하면 종료일자가 시작일자와 같아졌으면 좋겠어요~

만약에 시작일자가 12월 01일이고, 종료일자가 12월 02일이라고하면 

시작일자, 종료일자 선택시 달력을 똑같이 12월로 귀찮게 클릭해야해서요!

(1) 시작 & 종료일자가 동시에 있는 행사가 대부분이고, (2) 종료일자는 항상 시작일자보다 뒤에 있기 때문에~ 시작일자 선택하면 종료일자도 시작일자랑 같이 기본적으로 설정되면 덜 구찮지 않을깨 생각이 들었어요 !!

**Comment by leedoopal** [comment]
`시작일자 > 종료일자` 인 경우에 `시작일자 = 종료일자`가 되도록 바꿔두었어요!
의견주어서 고마워요~~!~!
