### ISSUE TITLE
로컬 빌드 오류

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#128]
@leedoopal 

반가워요~ 

로컬에서 admin을 돌리려고 하는데요!

.env파일에 다음과 같이 적었어요!

```
NEXT_PUBLIC_ADMIN_V1_URL={% 서버 Host 주소 %}
NEXT_PUBLIC_ADMIN_V2_URL={% 서버 Host 주소 %}
NODE_ENV=local
```

![스크린샷 2022-12-17 오후 11 39 20](https://user-images.githubusercontent.com/28642484/208247283-09187e02-3dac-4abe-a648-6f44f2498bf3.png)

로그인하니 이렇게 나오네요!

혹시 어떻게 로컬 실행해야할까요~?!

**Comment by KoEonYack** [comment]
@leedoopal 

선생님~~~

선생님이 보내준 환경변수를 .env 파일에 복붙해서요~

```
npm run build

npm run start
```

하고 관리자 로그인 시도시 위에 첨부한 사진처럼 같은 오류가 나서요~~~~!! 알수 없어요!!

**Comment by KoEonYack** [comment]
앗 이슈를 안닫았네요!!

알려주어서 고마워요~~~!!!

**Comment by leedoopal** [comment]
@KoEonYack 
저는 알려준게 없는데 잘 되었나요??

**Comment by KoEonYack** [comment]
@leedoopal 

카톡으로 보내준 환경변수 추가해서 실행하니 잘 되었어요!
