### ISSUE TITLE
모바일 베너 관리자 페이지 기획 검토

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#137]
@leedoopal 

잘 지내고 있어~?! 

네이티브 모바일을 개발 진행하면서 모바일 상단 배너를 추가하려고하는데!

관리자 페이지 기획을 해봤고, (별 문제 없을것 갖지만) 성화가 한번 스르륵 보고 문제 없는지 봐줄 수 있을까~? 

문제 없다면 화면을 기반으로 API를 만들어보려고해~!

> https://docs.google.com/presentation/d/1FJOr0_ry5z7W0-EALd9ib510mg27ivcVU9yFREYRfZE/edit?usp=sharing (1~3p)

**Comment by leedoopal** [comment]
@KoEonYack 헉 너무 늦게봤네;;; 미안해;;
다른 부분은 문제 없는데, 만약 우선순위가 동일하다면 어떻게 되는거야?
