### ISSUE TITLE
모바일 베너 관리자 페이지 개발 요청

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#138]
@leedoopal 

모바일 배너 관리자 페이지 요청하려고 하는데!! 요새 시간 괜찮을까아!? (앱의 속도로 보았을때는 2주안에 만들어지면 좋을텐데~ 부담되면 어느정도 걸릴지 말해주어도 좋고~)

https://github.com/brave-people/Dev-Event-Client/issues/137 요기에서 이야기해준대로 큰 문제는 없다구해서 개발에 API 배포해두었어

> Swagger: https://dev-brave-people.o-r.kr/swagger-ui/index.html#/%5B%EA%B4%80%EB%A6%AC%EC%9E%90%5D%20%EB%AA%A8%EB%B0%94%EC%9D%BC%20%EC%83%81%EB%8B%A8%20%EB%B0%B0%EB%84%88
> 기획서: https://docs.google.com/presentation/d/1FJOr0_ry5z7W0-EALd9ib510mg27ivcVU9yFREYRfZE/edit?usp=sharing (1~3p)

**Comment by leedoopal** [comment]
@KoEonYack 2주 정도로 잡고 해볼게!~!!

**Comment by leedoopal** [comment]
@KoEonYack dev에 올려놨어!! 보고 수정할 부분 있으면 알려줘!~!!!

**Comment by KoEonYack** [comment]
@leedoopal 


![Uploading 스크린샷 2023-04-28 오후 9.20.16.png…]()

**Comment by leedoopal** [comment]
@KoEonYack 그거 코드를 수정한게 있어서 쿠키 한번 날리고 해야돼..!

**Comment by KoEonYack** [comment]
@leedoopal 

아하!!!

시작일자를 선택 안하고 확인 누르면 필수값입니다. 빨간색 메시지가 없다..! 사소한거긴 하지만..,,,!!

<img width="736" alt="스크린샷 2023-04-28 오후 9 22 20" src="https://user-images.githubusercontent.com/28642484/235146140-26ee0800-e6f2-40b3-88f6-6364a0c94bcc.png">

**Comment by KoEonYack** [comment]
@leedoopal 

말고는 완벽한듯!!!! 

넘 빨리 만들어주어서 고마워~!!!!! 💯

**Comment by KoEonYack** [comment]
@leedoopal 

아직 리얼에는 API 배포는 안해서! 내일 오후중에 배포 예정이야~

배포하면 알려줄께!

**Comment by leedoopal** [comment]
@KoEonYack 헉 알겠어!!

**Comment by leedoopal** [comment]
> 시작일자를 선택 안하고 확인 누르면 필수값입니다. 빨간색 메시지가 없다..! 사소한거긴 하지만..,,,!!

고쳐놨어!!

**Comment by KoEonYack** [comment]
@leedoopal 

헛 아직 배포가 안된곤가!! 커밋은 있는것같은데 아직 메시지가 안나오네~

<img width="1132" alt="스크린샷 2023-04-28 오후 9 33 15" src="https://user-images.githubusercontent.com/28642484/235148387-1c852f0f-8e92-4c15-81c4-862913f17825.png"

--------------------------------------------

빨리 고쳐주어서 고마워~!!!

**Comment by KoEonYack** [comment]
@leedoopal 

리얼에 API 배포했어!!

**Comment by KoEonYack** [comment]
앗 버그가 있다. 

배너 생성 -> 종료 일자 -> 상시 체크시 9999년 12월 31일이 입력 되지 않고 빈 값으로만 나와!

<img width="1089" alt="스크린샷 2023-04-29 오후 2 55 53" src="https://user-images.githubusercontent.com/28642484/235286433-1111f46a-0830-4f00-9314-a88505
<img width="1077" alt="스크린샷 2023-04-29 오후 2 56 03" src="https://user-images.githubusercontent.com/28642484/235286437-132e39b4-32fe-46d6-8098-98a06dcac410.png">
53e70a.png">

**Comment by leedoopal** [comment]
@KoEonYack 
오 9999-12-31로 표시되면 해제 했을 때 2023년으로 돌아가기까지가 오래걸릴 것 같아서 일부러 빈값으로 둔건데.. 
그게 더 사용하기 편하다면 그렇게 바꿀게! 어떻게 생각해?

**Comment by KoEonYack** [comment]
@leedoopal 

아하~ 그러면 체크박스를 해제했을때

1. start_date가 입력된 경우 -> end_date를 start_date로 설정해줌
2. start_date가 힙력도지 않은 경우 -> end_date를 빈 값 처리

요렇게 정책을 정하면 어떨까~?

**Comment by leedoopal** [comment]
@KoEonYack 좋아~! 그렇게 수정할게!!

**Comment by KoEonYack** [comment]
좋아~~!! 🐥

**Comment by leedoopal** [comment]
@KoEonYack 운영에다가 올려놨어!!~!

**Comment by KoEonYack** [comment]
@leedoopal 와~~~ 고마워💯
