### ISSUE TITLE
cors error

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Client#14]
`https://sangjin-test.herokuapp.com/admin/v1/register/user` POST
로컬에서 호출하려는데 CORS 에러가 나네요;; 수정 가능할까요??

**Comment by KoEonYack** [comment]
@leedoopal 
그렇군요~ 확인해볼께요!

**Comment by KoEonYack** [comment]
spring에서 cors 설정을하고 배포했더니 헤로쿠에서 막아서 503 상태네요..!
확인후 다시 코멘트 남기도록할께요..!!

**Comment by KoEonYack** [comment]
![image](https://user-images.githubusercontent.com/28642484/147329634-5687bc36-dc73-4604-ac0f-6cbabb3de251.png)
-------------------------

<img width="834" alt="스크린샷 2021-12-24 오후 4 29 46" src="https://user-images.githubusercontent.com/28642484/147329668-88d213cc-dd3f-4cbf-a3a2-5115eaa7e7a6.png">

-------------------------

CORS 문제 해결했어요~ (제가 Dev-Event-Client 저장소 clone해서 잘 되는지 테스트해봤어요)
회원가입 스팩이 변경되었으니 확인해보세요!

서버는 새로 배포하면 기존 데이터가 사라지는 상태로 설정해두었어요!

**Comment by leedoopal** [comment]
제가 그동안 쭉 야근해서 지금봤네요;; 미안합니다,,
잘되는거 확인했어요! 고마워요

**Comment by KoEonYack** [comment]
@leedoopal 야근을 하였군요~ ㅠㅠ
22년에는 정퇴 많이 할수있기를 🏃🏃

**Comment by KoEonYack** [comment]
@leedoopal 야근을 하였군요~ ㅠㅠ
22년에는 정퇴 많이 할수있기를 🏃🏃
+ 너무 미안해하지 않아도 괜찮답니다! 저는 지금 와르르 API 만드는데 반년 걸렸거덩용..
