### ISSUE TITLE
모바일 배너 오류 및 입력 폼 추가

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#149]
@leedoopal 

안녕!! 반가워~~~~~

## [1] 버그
> https://d-dev-event-client.vercel.app/admin/banner

![스크린샷 2023-07-24 오후 10 25 40](https://github.com/brave-people/Dev-Event-Client/assets/28642484/0d89de9f-5f64-4cb8-b16f-b84ece90cd07)
지금 여기 접속했을때 오류가 나와!

----
## [2] 입력 폼 추가

![스크린샷 2023-07-24 오후 10 27 26](https://github.com/brave-people/Dev-Event-Client/assets/28642484/b22d8c5a-0af5-434d-97bd-0c03fd231cc4)
행사 배너 API GET/POST/PUT 필드에 `"eventLink": "string"` 를 추가했어. 이거는 배너 클릭했을때 이동할 행사 링크인데 이번에 앱 점검하면서 있으면 좋겠어서 추가했어!

----

**Comment by leedoopal** [comment]
@KoEonYack 
헉 버그 제보해줘서 고마워!! 행사링크는 required 필드지?!

**Comment by KoEonYack** [comment]
@leedoopal 맞이 필수필드야~

그런데 swagger에는 필수 필드로 안되어있을꺼야! 

아직 행사 링크 필드가 추가되지 않은 개발환경에서 필수필드로 만들어놓으면 

행사 링크 입력 폼 추가 전까지 새로운 배너를 등록할 수 없을것이기 때문이지!

**Comment by KoEonYack** [comment]
@leedoopal 헛~~!! 넘 로켓이야!! 고마워!!! >O<

**Comment by KoEonYack** [comment]
@leedoopal 

리얼에도 푸론트 배포 완료한거 확인했어!
리얼에도 API 배포 완료했어~

------------------------------------------

<img width="1250" alt="스크린샷 2023-07-26 오후 10 43 21" src="https://github.com/brave-people/Dev-Event-Client/assets/28642484/cdbefc72-2d81-47a3-b959-bd5e17670afa">

개발 어드민에서 14번 배너 클릭했을때 에러가 떨어지는데! 요거 배너 노출시간, 노출 종료시간이 없어서 그런건가!!?

**Comment by leedoopal** [comment]
@KoEonYack 
앗 맞아! 종료시간은 required 필드라서 없을거라 예상하지 않았거든
방어코드 추가해서 배포해놨어!!

**Comment by KoEonYack** [comment]
@leedoopal 앗 그렇구나~! 항상 들어가는게 맞긴하지....! 넘 고마워!!
