### ISSUE TITLE
login cors error

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Client#15]
![스크린샷 2021-12-30 오후 10 21 49](https://user-images.githubusercontent.com/39582981/147757075-59371bf0-0401-4a7a-acee-9f844d21cac4.png)
login을 만드려고 하니 회원가입처럼 cors error가 나는데.. 혹시 해결 가능할까요?

그리고 이슈는 아니지만.. 회원가입처럼 username과 user_id를 통일하면 좋을 것 같아요..!
바쁘면 안해도 되어요~!

**Comment by KoEonYack** [comment]
@leedoopal 
헉 완전히 해결된게 아니었군요...
회원가입은 CORS 이슈가 없는 것인가요?

**Comment by leedoopal** [comment]
@KoEonYack 
회원가입은 성공했답니다~! 고마워요

**Comment by leedoopal** [comment]
근데 로그인은 왜 나오죠..? 알 수 없어요..!

**Comment by KoEonYack** [comment]
그렇군요! 로그인 부분 코드 커밋이 가능하다면 스프링 설정 만져보면서 테스트해볼께요~!

**Comment by leedoopal** [comment]
오 네네! 지금 main branch에 있답니다

**Comment by KoEonYack** [comment]
인증쪽 cors 설정을 별도로하고 배포했는데도 문제가 발생하네요 !
제가 내일 더 살펴볼께요,,,!
다른 API는 로그인 안해도 호출가능하게 해두었어요!

**Comment by KoEonYack** [comment]
@leedoopal 

로그인시 CORS 이슈 해결하였습니다!

----------------

![스크린샷 2022-01-03 오후 6 53 12](https://user-images.githubusercontent.com/28642484/147917820-2d5728bd-c161-4e21-81d2-e09070b4ecdd.png)
![스크린샷 2022-01-03 오후 6 52 55](https://user-images.githubusercontent.com/28642484/147917799-b87ce85c-410e-4710-8c49-976661e4dbf6.png)
- 기본 계정은 id: admin, pw: 1234가 들어있어요!
- 스웨거는 환경변수로 빼는것이 어떨지 제안해보아요!?! 
- username -> user_id 로 변경하였어요!



새해가 밝았어요! ☀️ 새해복 많이 받고 올해도 즐거운 개발 해보아요!🌸,

**Comment by leedoopal** [comment]
@KoEonYack 
cors error 해결되었어요 고마워요! 하지만,, 다른 문제가 있어요,,,

cindy user_id로 가입했는데 아이디와 패스워드가 맞지 않다고 하네요..!
이유를 알 수 없어서 kindy user_id로 새로 가입했는데 마찬가지로 패스워드가 맞지 않다는데,, 왜그런지 알 수 있을까요?

새해 복 대왕 많이 받아요!!!!! api 만들어주어서 고마워요!

**Comment by leedoopal** [comment]
@KoEonYack 
아 왜 그런지 알 것 같아요! 해결 되면 클로즈 할게요!

**Comment by leedoopal** [comment]
@KoEonYack 
로그인 api만 형식이 x-www-form-urlencoded 였네요..! 이제 잘되어요!

**Comment by KoEonYack** [comment]
@leedoopal 맞아요....!

body에 넣을 순 있는데 쪼금 복잡해져서 일단 기본 방식으로 했어요.

그렇다고 크게 어려운것은 아니어서 API 일관성을 위해서 수정을 해볼께요!😅

**Comment by leedoopal** [comment]
@KoEonYack 
갑자기 로그인이 안되는데 혹시 무언가 스펙이 바뀌었나요,,???
x-www-form-urlencoded으로도 해보고 json으로도 호출해보았는데 둘다 안되네요;ㅅ;

**Comment by KoEonYack** [comment]
@leedoopal 윙 확인해볼께요!

**Comment by leedoopal** [comment]
@KoEonYack 앗 고마워용!

**Comment by KoEonYack** [comment]
![스크린샷 2022-01-10 오후 9 05 23](https://user-images.githubusercontent.com/28642484/148763496-3c7f64ee-74a6-46fc-b84b-d6c43cdd1e06.png)
잘되고있어용!
혹시 key값이 user_id 인지 확인해보세요~!!

**Comment by leedoopal** [comment]
ㅎㅎ,, 배포하면 데이터가 날라간다는 사실을 깜박했네요
다시 가입하니 성공하였어요! 금방 답변해주어서 고마워요!!;;

**Comment by KoEonYack** [comment]
헠 다행이에요~!!
맞아요! 배포시 DB는 clean-up한답니다ㅠㅜ
