### ISSUE TITLE
베너 관리자 페이지 기획 검토

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#151]
@leedoopal  반가워~~~

## 1. 배경 

모바일에서만 제공하는 배너를 웹과 동시에 제공하려고 하는데, 그러기 위해서는 관리자 페이지의 문구 수정과 배너 배경 색상 선택 관련 기능 추가가 필요해서 신규 기획을 만들게 되었어.

## 2. 활용처 

![image](https://github.com/brave-people/Dev-Event-Client/assets/28642484/feb9bd96-921a-43cc-8153-7ea74c34fb03)
> 신규 개편 작업중인 WEB, 빨간 영역에 들어가게 될 거야.

![image](https://github.com/brave-people/Dev-Event-Client/assets/28642484/02d83b70-9407-4131-ae26-52d986968073)
> 모바일 배너 영역

안드로이드 앱의 경우 막바지 작업이 남았고, 곧 출시를 앞두고 있어. 배너 기능을 잘 만들어주어서 안드로이드 앱에는 배너 기능이 들어가서 출시 될 수 있게 되었어. 고마워!!!

## 3. 기획서

- 기획서: https://docs.google.com/presentation/d/1FJOr0_ry5z7W0-EALd9ib510mg27ivcVU9yFREYRfZE/edit?usp=sharing (2~4p)
- 색상 선택 기능이 핵심인데, 기획서 보고 의견을 주면 좋겠어!

---------------------------
잘 지내고 있어~?

얼마전에 침착맨이 우리 회사와서 촬영하고 갔는데 유툽에 올라왔어! 나는 카메라 근처에 얼쩡거렸는데 편집되었구!

https://youtu.be/vk-xYUp0WtI 많관부!

**Comment by leedoopal** [comment]
@KoEonYack 
헉 미안..!! 요즘 갑자기 바빠져서 확인을 늦게했네ㅠ.ㅠ 
기획해준거 좋은거같아! 그렇게 만들어볼게 고마워~!!!!

---
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
어딨지?? 하면서 유심히 보다가 방긋 모습이 바로 보였어ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
소식 고마워ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by KoEonYack** [comment]
@leedoopal 

엄청난 ㅋ이다!!

확인 고마워! 주말에 API 잘업해볼께~!!

**Comment by leedoopal** [comment]
@KoEonYack 프론트 작업은 다 끝났어!! API 작업 완료되면 말해줘!~!!!

**Comment by KoEonYack** [comment]
@leedoopal 엇,,,!! 로켓 작업해주었는데 내가 알림을 놓쳤네 ㅠㅠ,,, API 연동해서 로컬 테스트 마치고 알려줄께!!

**Comment by KoEonYack** [comment]
@leedoopal 

로컬에서 어드민 올려봤는데 어떻게 이렇게 찰떡같이 원하는대로 만들어줄 수 있는거야~~~~~?! 정말 대단해~~~~~~~~!!! 👍 

API는 개발 환경에 배포했어~!!
테이블을 안전하게 신규 테이블로 만들어서 기존에 개발에 등록한 배너는 안보일꺼야~ 테스트를 하려면 다시 등록해야햇!

1. 어드민 URI에 mobile이 제거했어~
2. backgroundColor 필드가 생겼고 필수 필드야!

![스크린샷 2023-09-02 오후 3 30 11](https://github.com/brave-people/Dev-Event-Client/assets/28642484/d40ae4f0-d680-4f80-a31a-a0d5a8c328c4)

------------------------------------------------------------

# 의견!
![image](https://github.com/brave-people/Dev-Event-Client/assets/28642484/e3eedf10-0b33-4c4a-98d5-ed5a97286fdc)
> 노출여부는 default checked였으면 좋겠어!! 이것은 예전에 말하고싶었는데!! 이번에 바꾸는김에 하면 좋을듯!!

----------

![image](https://github.com/brave-people/Dev-Event-Client/assets/28642484/934852a7-d0f1-4869-a8b9-36561c0c2604)
> 모바일 -> 최상단으로 문구가 변경하면 될것같아!

----------

![image](https://github.com/brave-people/Dev-Event-Client/assets/28642484/e3fb68f3-38dd-44c1-8a46-21674c01299e)
> color picker가 너무 하단에 치우쳐져있어!!

----------

![image](https://github.com/brave-people/Dev-Event-Client/assets/28642484/ff718e08-6421-4742-be96-094f6da330f7)
> 가끔 색상이 엉뚱한게 보일때가 있는데 재현은 안되네 ㅠㅠ,,,

----------

**Comment by KoEonYack** [comment]
@leedoopal 

수정 넘 고마워 >0<

----------------

```json
{
    "title": "테스트",
    "event_link": "11",
    "priority": 1,
    "visible_yn": "Y",
    "start_date_time": "2023-09-05T00:00",
    "end_date_time": "2023-09-26T00:00",
    "banner_image": "https://brave-people-3.s3.ap-northeast-2.amazonaws.com/dev/DEVEVENT/2023-09-05-00-15-3950-a34564dd.png",
    "background_color": "#03878c"
}
```

![스크린샷 2023-09-05 오후 12 09 28](https://github.com/brave-people/Dev-Event-Client/assets/28642484/0a8c69c2-1f9f-4fb7-9e7f-18668a777535)

이렇게 실행해야해~ 스네이크 케이스로 보내는것은 여전해!

-----------

에러 메시지에 카멜 케이스로 메시지가 내려오는것은 스프링부트에서 지정된 기본 메시지여서 그래~ 
이것을 커스텀하려면 메시지를 필드마다 지정해야하는데,, 상당한 귀차니즘에 빠져서 ㅠㅠ,,, 
우리끼리는 스네이크로 보내야한다고 정하면 되니깐!! 
지나고보니 스네이크보단 카멜로 했어야했는데 생각도 들고 ; ㅅ ;

**Comment by leedoopal** [comment]
@KoEonYack 
아하 그렇구나~~!! ㅋㅋㅋㅋ아냐 이유 알려줘서 고마워!
 dev에다가 올려놨어 😸

**Comment by KoEonYack** [comment]
@leedoopal 

![스크린샷 2023-09-07 오전 12 35 55](https://github.com/brave-people/Dev-Event-Client/assets/28642484/0a3fe2bb-fac3-423a-a1d1-78064f0a18bd)
![스크린샷 2023-09-07 오전 12 36 02](https://github.com/brave-people/Dev-Event-Client/assets/28642484/f9fe9b91-a6ac-4698-a906-4d08cdd0a7ba)

아직 모바일이라는 표현이 남아있다!! 

서버에서 배너 등록할때 응답값을 201 status code로 변경한다면 프론트에서 코드 변경이 필요할까~~?!

**Comment by leedoopal** [comment]
@KoEonYack 
헉 모바일 > 최상단으로 전부 수정했어!~!

응답값을 변경하게 되면 프론트에서도 코드를 바꿔줘야하는건 맞는데
지금 배너 생성하면 201로 내려오는 것 같은데?! 
프론트에서는 예전부터 배너 생성시 status_code 201이라면 -> 성공으로 처리하고 있었어..!
<img width="647" alt="스크린샷 2023-09-07 오후 11 45 05" src="https://github.com/brave-people/Dev-Event-Client/assets/39582981/5aa15254-61e8-431a-93e0-f431b7261ebd">

**Comment by KoEonYack** [comment]
@leedoopal 

너무 늦었지...? 😅

해당 작업건 리얼에 배포 완료했어! 

웹 혹은 ios 런칭하면 배너 제작 과제랑 함께 배포하려고 했는데.. 

늦어져서 개발 서버에만 배포하고 있는것보다 일단 리얼에 배포하는게 좋을것 같아서 리얼에 배포했어..!! (간간히 안드 앱에서 슬슬 하나씩 등록해볼 예정!!)

엄청 빨리 만들어주어서 고마워! 색상 선택하는것은 아무리 생각해봐도 넘 잘 만들어진것 같아!! 넘 고마워!!!

**Comment by KoEonYack** [comment]
@leedoopal 

리얼 배포해주었네~~!! 넘 고마워!!! 👍 💯

**Comment by leedoopal** [comment]
@KoEonYack 
분명 api 리얼 배포했다는 메일을 받았는데.. 내가 리얼에 배포를 안했더라구;;!!
부랴부랴 배포했어ㅠ.ㅠ 고마워 확인해줘서!!
