### ISSUE TITLE
master -> main branch 이동

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Client#16]
저에게 setting 권한이 없어서 부탁해요! :)

default branch master -> main으로 바꾸어 줄 수 있나요?

**Comment by KoEonYack** [comment]
와~ 지금까지 저장소 관리자 권한이 없었군요! Admin 권한을 주었어요!

----------

![스크린샷 2021-12-30 오후 10 44 26](https://user-images.githubusercontent.com/28642484/147757420-fbcc2218-b8cf-4e5d-a33e-8e6d2c5eeb51.png)
main 브랜치가 있다고하네요~!

**Comment by leedoopal** [comment]
ㅋㅋㅋㅋㅋㅋ고마워요!
