### ISSUE TITLE
📮 [Server TEAM - 작업 공유] 태그 API 

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#17]
@leedoopal 

즐거운 화요일 보내었나요~~?!  😃 
현재 작업 사항 공유 & API 변경 스팩을 알려드리고 싶어서 issue 남겨보아요!

--------------------

## 현재
![스크린샷 2022-01-04 오후 7 38 18](https://user-images.githubusercontent.com/28642484/148046915-a5bc28e7-5ad2-48df-8a51-354fc030a6b8.png)
현재 개발자 행사, 다시보기의 경우 태그는 공통 API를 사용하고 있어요! 

## 변경사항 
개발자 행사 태그 CRUD, 다시보기 태그 CRUD를 별로로 분리하는 방향으로 가려고합니다!

```text
- 행사 다시보기에 등록할 태그 생성 [POST] /admin/v1/replayEvents/tags
- 행사 다시보기에 부여 가능한 태그 전체 조회 [GET] /admin/v1/replayEvents/tags
- 행사 다시보기에 부여 가능한 태그 삭제 [DELETE] /admin/v1/replayEvents/tags/{tagId}
- 행사 다시보기에 부여 가능한 태그 수정 [PUT] /admin/v1/replayEvents/tags/{tagId}
```
```text
- 개발자 행사에 등록할 태그 생성 [POST] /admin/v1/events/tags
- 개발자 행사에  부여 가능한 태그 전체 조회 [GET] /admin/v1/events/tags
- 개발자 행사에  부여 가능한 태그 삭제 [DELETE] /admin/v1/events/tags/{tagId}
- 개발자 행사에  부여 가능한 태그 수정 [PUT] /admin/v1/events/tags/{tagId}
```

## 예상 작업일
- 이번주 주말 개발서버 배포 예정이에요
- 일정이 바뀐다면 알려드리겠어요!
- 배포 완료하면 해당 이슈에 맨션해서 알려드릴께요! 
- 배포 후 해당 issue를 닫겠어요!

--------------------

오늘 메일로 데브 이벤트 웨일 확장앱을 운영 안하냐는 문의를 받았어요! (+ 메일을 보고 확장앱은 비공개로 설정 신청하였어요..!)
아주 예전에 보여주었지만 웨일 확장앱 저장소는 [여기](https://github.com/whale-lab/dev-event) 있어요!
우리 서비스를 잊지 않고 찾아주는 분이 있다니 너무 감사하답니다~

오늘 하루 고생했어요
평화로운 밤 보내요! 🌙

**Comment by leedoopal** [comment]
고마워요! 저는 이번주 풀 야근해서.. 이제 보았습니다...........
천천히 해주어요 저는 다음주부터는 아마.... 할 수 있지 않을까 싶어요......

**Comment by leedoopal** [comment]
태그 api가 더 깔끔해졌네요:) 고마워요! 주말 잘보내요!!

**Comment by KoEonYack** [comment]
@leedoopal 

헠!!! 풀🌿 야근을 하였군요! (´Д｀)。 

그간 와르르 API가 되지 않도록 많이 테스트하고 개선하고 있을께요~!!

**Comment by KoEonYack** [comment]
@leedoopal 

개발 서버 배포 완료하였어요!

![스크린샷 2022-01-10 오후 7 46 32](https://user-images.githubusercontent.com/28642484/148753659-eb20c5e5-7ac7-40eb-8a3d-5156c3660163.png)
![스크린샷 2022-01-10 오후 7 46 49](https://user-images.githubusercontent.com/28642484/148753694-d0ff56a1-f9d7-4a10-aa4b-fef33424e870.png)

개발자 행사, 개발자 행사 다시보기 태그 API와 DB 분리하였어요!

이슈는 닫겠어요~~!
