### ISSUE TITLE
📮 [Server TEAM - 작업 공유] JWT, API 권한 설정

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#18]
@leedoopal 

잘 지내고 있나요~?! 🏡
저도 회사일이 많아지네요,,,  🥺🥺🥺

Server TEAM의 작업 공유를 해드리겠어요!

--------------------------------
## 현재
- 관리자 페이지 API는 테스트를 위해서 토큰을 보내지 않더라도 API를 호출 할 수 있어요!

### 접근 제한
![스크린샷 2022-01-10 오후 8 11 27](https://user-images.githubusercontent.com/28642484/148756951-a5857052-f1d0-4b23-8007-0c2bbe0c5de3.png)
- 관리자 API에 해당하는 모든 API에 대해서 토큰이 있어야 호출할 수 있도록 수정하겠어요!
- JWT에서 ROLE은 리스트로 받을 수 있게 설계는 되어있어요!(일반적으로는 단일 값이 담기겠지만요) ROLE_ADMIN과 ROLE_MANAGER 두 가지 권한일때만 API 호출 가능하게 할께요

### JWT 만료 시간 설정
- 개발 토큰 만료 시간 
  - access token 만료 시간 30분
  - refresh token 만료 시간 1주일
- 상용 토큰 만료 시간
   - access token 만료 시간 30분
   - refresh token 만료 시간 1일
--------------------------------
## ☁️  진행 공유
- 위의 작업은 이번주 내로 완료하겠어요!
- 개발 & 상용은 헤로쿠에서 Oracle Cloud로 전환 예정이에요! 전환 완료하면 알려드리겠어요!
--------------------------------

이번주도 힘을 내보아요!
평화로운 밤 보내요! 🌙

**Comment by leedoopal** [comment]
@KoEonYack 
오 고마워요! 그렇게 작업할게요!
오늘은 여유가 있어서 작업 가능할 것 같아요~!
파이팅 하는 한 주를 보내보아요! 👍 👍 👍

**Comment by KoEonYack** [comment]
@leedoopal 

이번 이슈에 해당하는 개발건을 배포하였어요~
토큰이 잘못될 경우 `null` 을 응답해서 API를 사용할때 적잖아 당황했을것 같아요!
좀 더 좋은 사용을 위하여 많은 고민을 하였고 이번 개발에 담아봤어요!
지금까지 개발한 js를 코드보니,, JWT 부분을 작업하셔서 새롭게 변경한 방식대로 변경해야할것 같지만  ㅜㅠ 멋찐 방법으로 바꾸었답니다...!

지금부터 토큰 사용에 중요한 변화를 설명해드리겠어요!

------------------------------------------


## 변경 1. 로그인 방식 변경

<img width="497" alt="스크린샷 2022-01-16 오후 4 46 02" src="https://user-images.githubusercontent.com/28642484/149651757-c8b98828-e4f4-44a4-baaa-04cfbf534e58.png">

- 이전에는 x-www-form-urlencoded로 id, pw를 보냈어요.
- 개선한 방법으로는 response body에 json으로 넣으면 된답니다!

<img width="723" alt="스크린샷 2022-01-16 오후 4 49 31" src="https://user-images.githubusercontent.com/28642484/149651847-47fdce48-5fe2-461d-b9e8-5d19f335670c.png">

- 지금까지 로그인 API swagger가 없어서 당황했을텐데요! 이번에 만들었습니다
- 개발, 상용 환경에따른 토큰 유효시간 설명도 넣었어요~

------------------------------------------

## 변경 2. JWT 토큰 request 방식 변경

<img width="796" alt="스크린샷 2022-01-16 오후 4 53 22" src="https://user-images.githubusercontent.com/28642484/149651908-611fe162-1eb1-4372-901e-d1fcd691d792.png">

- Bearer 방식에서 Authorization 헤더에 토큰을 담는 방식으로 변경하였습니다!

------------------------------------------

## 변경 3. API 접근 권한 설정

<img width="389" alt="스크린샷 2022-01-16 오후 4 55 37" src="https://user-images.githubusercontent.com/28642484/149651967-61a359b9-ad40-4c5e-84b8-006384748991.png">

<img width="461" alt="스크린샷 2022-01-16 오후 4 56 24" src="https://user-images.githubusercontent.com/28642484/149651984-ae1f5a07-2628-4b84-aecf-5a9a82288ca6.png">

<img width="375" alt="스크린샷 2022-01-16 오후 4 57 00" src="https://user-images.githubusercontent.com/28642484/149652006-301c723f-b0b4-4cdb-9f32-93641e8a44f0.png">

- 지금까지 API에 토큰을 담아 보내도 권한을 검사하지 않고 실행이 가능했어요!
- API 접근 권한을 swagger에 담았어요

------------------------------------------

## 변경 4. 토큰 에러 메시지 상세

- 지금까지 토큰에 문제가 있으면 null을 응답했어요. 정말 충격이었을것같아요!

<img width="607" alt="스크린샷 2022-01-16 오후 4 57 45" src="https://user-images.githubusercontent.com/28642484/149652026-f97add7f-46fe-43e2-8125-46ab221ad6bc.png">

<img width="578" alt="스크린샷 2022-01-16 오후 4 57 57" src="https://user-images.githubusercontent.com/28642484/149652028-8eda633d-9dad-4b1c-bcf5-28582b120630.png">

<img width="416" alt="스크린샷 2022-01-16 오후 4 58 08" src="https://user-images.githubusercontent.com/28642484/149652036-4b17d4c8-659a-4564-b7b0-ac491f4d78ce.png">


<img width="456" alt="스크린샷 2022-01-16 오후 4 58 31" src="https://user-images.githubusercontent.com/28642484/149652045-fe1f288c-44ca-4969-ac3a-f2abad04a309.png">

- 토큰의 상태에 따라서 에러 메시지 응답을 재설계하였어요!

------------------------------------------

## 변경 5. Swagger 설명 변경 

<img width="816" alt="스크린샷 2022-01-16 오후 4 50 30" src="https://user-images.githubusercontent.com/28642484/149651864-a667c29d-7a50-4e8b-8113-28459d7b8bab.png">

- 리프래시 토큰을 이용한 JWT 토큰 재발급 API 설명이 명확하지 못해서 명확하게 변경하였습니다.

------------------------------------------

고마워요!

**Comment by leedoopal** [comment]
![스크린샷 2022-01-22 오후 7 44 57](https://user-images.githubusercontent.com/39582981/150635333-ea19f9bb-fe9e-4896-8616-5b0ada72e804.png)
회원가입할 때 쓰는 
1. register/id
2. register/email
3. register/user

세 api가 모두 400이 나오네요;; 이번에 바뀐 대로 적용 했는데 무엇이 문제일까요..?

**Comment by KoEonYack** [comment]
@leedoopal 헠,,,,!! 확인해볼께요..

**Comment by KoEonYack** [comment]
@leedoopal 

```
register/id
register/email
register/user
```



해당 API의 Authorization 토큰에 ROLE_ADMIN 권한을 갖고있는 관리자 토큰을 넣은게 맞을까요?! (디폴트 테스트 관리자 계정은 id: admin / pw: 1234) 이에요!

![스크린샷 2022-01-22 오후 7 51 04](https://user-images.githubusercontent.com/28642484/150635546-db554d77-c46e-44eb-8675-e826d9a9828a.png)

------------------------------

- Admin의 가입 API는 정확히는,, 관리자 계정 발급이에요! (사용자 가입은 아직 만들진 않았지만 네이커/카카오/깃허브 OAuth로 처리할꺼에요!)
- Admin 페이지의 관리자 계정을 발급해줄 수 있는 사람은 ROLE_ADMIN 권한을 소유한 사람만 가능해요!
- 관리자계정은 Admin 페이지에 접근할 수 있는 ROLE_ADMIN, ROLE_MANAGER(roles의 code) 계정을 소유한 이용자를 말한답니다 

![스크린샷 2022-01-22 오후 7 52 42](https://user-images.githubusercontent.com/28642484/150635604-4268e2bc-cd2a-4bbf-bab1-8cd8e993b280.png)

**Comment by KoEonYack** [comment]
![스크린샷 2022-01-22 오후 8 01 25](https://user-images.githubusercontent.com/28642484/150635834-6212acb1-4955-4752-b4e6-5cc5a668282c.png)
( 기획서 39p. ROLE_ADMIN을 소유한 사용자가 회원관리 탭 클릭 ) 

------------------------
![스크린샷 2022-01-22 오후 8 02 05](https://user-images.githubusercontent.com/28642484/150635851-bc2d0cda-b4f9-412a-a663-c9a730dfc71e.png)
( 기획서 41p. ROLE_ADMIN을 소유한 사용자가 회원관리 메뉴에서  계정 생성 클릭 ) 

------------------------

이렇게 만든 이유는 ADMIN 페이지에 접근할 사람이 많지 않을것이라 생각하고,, 
ADMIN 페이지 가입 폼을 외부에 노출하지 않으려고했어요...!
기획서에 의도가 잘 담기지 않았던것같아서 추가설명을 해보았어요!

**Comment by leedoopal** [comment]
이제 완전히 로그인과 가입에 성공했답니다!
그런데 궁금한 점이 회원가입 성공 후 플로우를 어떻게 해야할지 고민인데요,
일반 유저 가입이라면 홈으로 돌려보내겠지만 이건 타인의 계정을 가입해주는거다보니..
'성공적으로 가입되었습니다'라는 메시지 같은걸 노출시켜주는게 나을지 고민이에요..!!

**Comment by KoEonYack** [comment]
@leedoopal 

대단해요!!! 한발자국 전진했어요!

성공 flow가 기획에 안담겨있군요!

가입에 성공했다면 상단 중앙에 알림으로 가입 성공했다고 알려주고요

![스크린샷 2022-01-22 오후 9 55 50](https://user-images.githubusercontent.com/28642484/150639435-5d122262-4c15-4566-82bb-fab1e0a404b6.png)

(대충 이런식으로..)

![스크린샷 2022-01-22 오후 9 56 30](https://user-images.githubusercontent.com/28642484/150639467-bf0eae4f-c988-46cb-9f19-2825d440f9d5.png)
요 페이지로 이동하면 될것같은데 어떤가요~?!

**Comment by leedoopal** [comment]
아 고마워요!! 그렇게 만들게요!!!
