### ISSUE TITLE
refresh-token 관련 질문

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Client#19]
토큰을 셋팅하고 사용하려는 중인데 
`[GET] https://sangjin-test.herokuapp.com/admin/v1/token/refresh`
이건 어떻게 쓰는걸까요..?

refreshToken을 가지고 api를 호출하면 새 accessToken이 생길 줄 알았는데
```
{
  status_code: 50001,
  status: 'AUTH_500_01',
  message: '리프래시 토큰을 찾을 수 없습니다.'
}
```
요 에러가 나오네용..!

제가 잘못 이해하고 있는거라면 설명 부탁드려요..!! 🙇

**Comment by KoEonYack** [comment]
@leedoopal

헠 토큰을 하고있었군요,,,, 사실 해당 부분에 문제가 있어서 오늘 해당 버그를 고쳤는데요~

제가 지금 로켓배포를 해둘께요,,!

![스크린샷 2022-01-10 오후 10 44 53](https://user-images.githubusercontent.com/28642484/148776264-f17b4983-3cb6-40f8-bc45-e5f9e3f90125.png)

Authorization을 key로 `Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlzcyI6Imh0dHA6Ly8xMjcuMC4wLjE6OTAwMC9hZG1pbi92MS9sb2dpbiIsImV4cCI6MTY0MjQyMDYwM30.KSRWBW1ge4RnVOrpam94VJRVXMHPYv4KgMIlBNytqrI`

이렇게 `Bearer` 공백 토큰이 들어와요!

토큰쪽을 워낙 예전에 만들어두어서 자잘한 버그가 있을수 있는데요~ 이번에 권한 작업하면서 수정해둘께요ㅜㅜ

**Comment by leedoopal** [comment]
아하 이 방법으로 쓰는군요! 로켓 답변 고마워요!! 배포 끝나면 말해주세요 :)

**Comment by KoEonYack** [comment]
@leedoopal 

로켓 배포를 마쳤어요!

와르르 API가 좀 부끄럽네요 흑흑,,,

**Comment by KoEonYack** [comment]
@leedoopal 

로켓 배포를 마쳤어요!

와르르 API가 좀 부끄럽네요 흑흑,,,

> 이미 알고있겠지만 Authorization의 value로 넣는 Bearer 토큰은 Refresh Token을 넣어야한답니다! swagger에는 리프래시 토큰 발급이라고 써있는데 정확하게 쓴다면 리프래시 토큰을 이용한 accessToken 재발급이 되겠네요!

**Comment by leedoopal** [comment]
@KoEonYack 
고마워요..!
에러로그가 바뀌었어요

```
 {
  status_code: 50002,
  status: 'AUTH_500_02',
  message: '리프래시 토큰 발급중 서버 오류가 발생하였습니다.'
}
```

헤더에다가 잘 넣었는데..;; 알 수 없네용😢

**Comment by leedoopal** [comment]
필요하면 refresh-token을 주거나 혹은 코드를 커밋할 수 있어요!

**Comment by KoEonYack** [comment]
@leedoopal 리프래시를 주세용~

**Comment by KoEonYack** [comment]
@leedoopal 

해당 문제는 만료된 토큰을 보냈기에 발생한 문제로 정리되었습니다!

이번 권한 수정 작업에서 리프래시 토큰으로 엑세스 토큰 발급시 문제가 발생하면 에러 메시지를 담아서 보내드릴께요!

고마워요!!

**Comment by KoEonYack** [comment]
@leedoopal 

토큰 사용방식을 변경하였어요!
https://github.com/brave-people/Dev-Event-Client/issues/18 에 설명해두었답니다!!
