### ISSUE TITLE
대다네요 👏👏👏👏👏  배포(?)

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#2]
@Woohwahwa 

![image](https://user-images.githubusercontent.com/28642484/101279115-65dd6e80-3803-11eb-929c-06bad99f2582.png)

### 엄쳥나요!!!!!!!!!!!!!!!!!!!!!!

----

```JSON
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "predeploy": "npm run build", <- 추가
    "deploy": "gh-pages -d build", <- 추가
```
제가 알고있는 gh-page를 통한 배포를 하기 위해서
 __package.json__에 위와 같이 추가하고 npm run deploy를 했는데 새 하얀 화면만 나와요 ㅠㅠ
https://brave-people.github.io/Dev-Event-Client/ <-- 흰 도화지!
어떻게하면 gh-page로 배포할수 있을까요 ❓

**Comment by Woohwahwa** [comment]
제가 배포해서 올려놓았습니당! package.json 에 해당 로직 추가해놓았고, 배포는 똑같이 npm run deploy 하면 됩니다!! 풀 받은 후 npm install 한번 진행해주세요 :) @KoEonYack

**Comment by KoEonYack** [comment]
@Woohwahwa 헠,,,, 너모 감쟈해여!!!!!
