### ISSUE TITLE
[화면 설계] framer 디자인 목업 공유

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#20]
<img width="1190" alt="스크린샷 2022-01-16 오후 5 01 32" src="https://user-images.githubusercontent.com/28642484/149652118-d2ab83bc-5308-4fce-9d95-88f8e5ef685a.png">

- 위 사진은 익숙한 구글 슬라이드의 기획안이에요!
- 디자인적으로 명확하게 공유하고 싶다는 고민을 했어요!.. 
- 더구나 관리자 페이지에서 사용자에게 보여지는 메인 페이지 작업을 위해서 좀 더 우아한 디자인 결과물을 공유하는 좋다고 생각이 들었어요!

----------------------------------------

<img width="1728" alt="스크린샷 2022-01-16 오후 5 04 04" src="https://user-images.githubusercontent.com/28642484/149652160-d6199b1a-17f4-4f00-bf06-0417899d8bef.png">

- framer로 요렇게 만들어보았어요! (그런데 만드는데 엄청난 시간이 걸렸어요..)
  - webflow도 써봤는데.. 쉽게 쓰기에는 framer가 좋더라고요...!
- 태생이 디자인과 거리가 멀어서,, 최선을 다해보았어요!
- framer 계정을 만들고 알려준다면(google 계정으로 3초면 만들어요!) framer 작업 공간에 초대해드릴께요!
- framer 작업공간에 들어오면 사용한 색상을 볼 수 있어요!

**Comment by leedoopal** [comment]
framer 사용하기 쉽지 않았을텐데 대단해요..! 👍  좋아요를 드릴게요!
제 계정은 1233wsh@gmail.com 이랍니다 고마워요! 
이번주 너무 바빠.. 작업을 하나도 못해서 주말에 하려고 지금 열심히 하고있어요!!!!!!!!

**Comment by leedoopal** [comment]
추가로 디자인 같은 경우는 어떻게 만들지 계속 고민중이랍니다
css framework 쓸지, 많지 않으니 그냥 제가 만들지..
사용한다면 어떤걸 사용해볼지 등등 고민중이라... 일단 만드는걸 먼저 하고 있어요!

**Comment by KoEonYack** [comment]
@leedoopal 

https://www.codenary.co.kr/calendar/month

이거 봤는데 캘린더 스타일이 넘 탐나보이더라고요!!!  멋진 프론트세계에요!

**Comment by KoEonYack** [comment]
이슈는 닫을께요~!
