### ISSUE TITLE
🖼️ [화면 기획] framer -> figma 전환 안내

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#25]
@leedoopal 

어제 개발한 행사 등록 form 부분을 잘 보았어요! 대단해요~👏

관리자 화면은 화면 기획(목업?)을 생략하기로 하였으나 막상 앙상한 input form을 보자니 디자인 가이드라인은 있으면 좋을것 같아서 

오늘 figma를 공부해서 만들어봤어요! (framer를 공부한 시간이 아깝지만.. figma가 대세니깐요..)

![image](https://user-images.githubusercontent.com/28642484/152973058-6b080fa2-00a6-42b6-a363-6c585af1eb34.png)
( 👆️ 이전에 개발한 framer )

![스크린샷 2022-02-08 오후 7 57 49](https://user-images.githubusercontent.com/28642484/152973842-1eb3afba-af2f-414b-bf8f-31518e09b400.png)

![스크린샷 2022-02-08 오후 8 02 55](https://user-images.githubusercontent.com/28642484/152974589-ca9bcafb-1148-48e1-9a05-8824930ce64f.png)

( 👆️ 신규 작업한 figma ) 

[이전 이슈](https://github.com/brave-people/Dev-Event-Client/issues/20)에 남긴 gmail로 read & write 권한이 있은 figma 초대 메일을 보냈어요!

원하는 디자인의 방향과 맞을지는 모르겠네요... 

디자인 가이드라인이기에 세부 부분은 수정하면 되겠어요!

어디까지나 가이드라인이여서.. 다 만들기에는 시간도 어마어마하게 들어서 필요한 컴포넌트, 종류별 화면 정도는 만들 수 있을것같아요!

-----------------------------

<img width="471" alt="스크린샷 2022-02-08 오후 7 58 44" src="https://user-images.githubusercontent.com/28642484/152973994-c588be08-e4a6-4565-ac00-3ee16102d15c.png">

디자인 목업 이야기와는 별개로 지금 개발한 이벤트 생성 부분을 보면 시간을 필수로 입력해야하는데요~

사실 시간이 없는 행사가 있어서 시간은 별도로 입력받아야해요!

API상에서 start Time, end Time 필드가 공백이면 시간이 없는 행사라고 판단할꺼에요!

-----------------------------

고마워요~!

**Comment by leedoopal** [comment]
앗 고마워요~ 많은 도움이 될 것 같아요!
ㅋㅋㅋㅋㅋㅋinput form이 좀 앙상하긴하죠,,
디자인은 이벤트 조회/생성 api 연결까지 모두 마치고 나서 붙일 생각을 하고 있어요~
아직 갈 길이 머네요..!

---
![스크린샷 2022-02-08 오후 9 42 06](https://user-images.githubusercontent.com/39582981/152989246-1cfac4a2-08e2-4d55-b505-0cb29aee87bd.png)
재밌는 개그를 찾았어요~

![스크린샷 2022-02-08 오후 9 42 51](https://user-images.githubusercontent.com/39582981/152989396-8573efca-0153-44fa-9e7e-88a3867ebea8.png)
상진님도 찾았어요~

**Comment by osj3474** [comment]
우아.. ㅋㅋㅋㅋㅋㅋㅋㅋ 피그마 살짝 보고 나가려고 했는데, 캐치를 하셨군요 😧
성화님 작업 중이신줄 알고, 방해될까봐 바로 나왔습니다 ㅋㅋㅋㅋ

@KoEonYack 
풀스택을 넘어 디자인까지 가시는 건가요..!

**Comment by leedoopal** [comment]
@osj3474 
앗 보아도 괜찮아요~ 저는 상관없답니다..!

@KoEonYack 
헉 그러게요! 디자인까지 가는건가요....!!! 😎

**Comment by KoEonYack** [comment]
잡부가 되는것 같아요~~ 😵‍💫

백만 하다가 얼렁뚱땅 디자인 해보니 재밋긴하네요!!

**Comment by KoEonYack** [comment]
확인하였으니 이슈 종료합니다~!
