### ISSUE TITLE
🐞 [bug] image upload

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Client#27]
그동안 api 호출할 일이 없었는데 오늘 호출을 해보니
로그인을 제외하고 이벤트 조회, 이미지 업로드 시도했을 때 토큰 검증에 실패했다고 나와요;ㅅ;
무엇이 잘못 된걸까요..?

![스크린샷 2022-02-15 오후 9 57 42](https://user-images.githubusercontent.com/39582981/154066695-8fd9e160-d821-4e1e-97f1-30feaaccaa80.png)

**Comment by KoEonYack** [comment]
@leedoopal 

이벤트 조회는 되는데 이미지 업로드는 문제가 있어요 ㅠㅠ 살펴볼께요!!!

**Comment by KoEonYack** [comment]
@leedoopal 

개발서버 호출하는데 문제는 없어요~

제가 테스트할때 문제가 있었던것은 Postman에 존재하지 않은 파일을 보내서 그런거였어요 !!

![image](https://user-images.githubusercontent.com/28642484/154271913-d028155b-10fd-4d61-831d-ea466dc7c98f.png)

**Comment by leedoopal** [comment]
@KoEonYack 
같은 토큰으로 이벤트 조회는 되는데, 이미지 업로드는 안되어요;;
에러메시지는 이슈에 남긴것처럼 토큰 검증에 실패하였다는데 무엇이 문제일까요??

**Comment by KoEonYack** [comment]
@leedoopal 

앗.. body에 key값을 안알려주었네요 (흐엉엉..)

![스크린샷 2022-02-17 오전 8 47 40](https://user-images.githubusercontent.com/28642484/154376674-6e257995-5e12-4afe-ba0c-54ffe6a009bf.png)

images로 보내보세요~~!

**Comment by leedoopal** [comment]
@KoEonYack 
오 고마워요~~ 성공했어요!
