### ISSUE TITLE
🐞 getTags certificate error

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Client#29]
태그를 만드려고 getTags를 조회했는데 

```
reason: unable to verify the first certificate
```

라는 에러와 함께 조회에 실패했어요;;

이미지 업로드 api는 잘되는데 왜 태그 조회는 안되는걸까요..??
혹시 이유를 알고 있나요??

**Comment by KoEonYack** [comment]
@leedoopal

헠 그렇군요! 이유를 알아볼께요! 🐞

**Comment by leedoopal** [comment]
@KoEonYack 
와 로켓 답변 너무 고마워요ㅜㅜ!!

**Comment by KoEonYack** [comment]
@leedoopal 

ㅋㅋㅋㅋㅋㅋ로켓 답을 들고왔어요!


![스크린샷 2022-02-25 오후 11 09 13](https://user-images.githubusercontent.com/28642484/155729144-531fc345-4e0a-42f8-9021-27a063690b9e.png)

[GET] `/admin/v1/events/tags` 는 문제가 없어보여요!

오늘 22:26에 토큰 만료 로그가 남아있는데 이게 문제가 아닐까요?ㅅ?

**Comment by KoEonYack** [comment]
@leedoopal 

사설 SSL 처리 못하는 부분이 있군요...

서버에서 SSL 관련해서 변한건 없어요!

SSR <--> 사설 SSL 관련해서 도움을 줄 수 있는게 있을까요...?!

**Comment by leedoopal** [comment]
@KoEonYack 
그렇군요...! 
찾아봐야할 것 같은데요,, 선생님이 이미 알고 있는 지식이 있을까요??
프론트에서 이렇게 하면 될 것 같다~ 같은거요!

**Comment by KoEonYack** [comment]
@leedoopal 

제 PC와 [gitpage dev event client](https://brave-people.github.io/Dev-Event-Client/auth/signIn)에서는 이상이 없는걸로 봐서는 선생님의 PC에서 SSL 사설 인증한 Issuer R3를 처리하지 못하는것 같아서요...!

혹시 postman에서 개발 API 호출시 이상이 없나요?

혹은, 파이어 폭스에서 Issuer R3 인증서를 인증해주는 브라우저여서 localhost 접속을 파이어폭스에서 해보는것은 어떨까요...?

**Comment by KoEonYack** [comment]
@leedoopal 

혹시 해결하였나요~~?!

너무 안된다면 알려주세요! 개발 서버는 http 통신이 가능하도록 열어놓을께요~!

**Comment by KoEonYack** [comment]
@leedoopal 

개발서버 http 9000번 포트로 열었어요~

<img width="1089" alt="스크린샷 2022-03-01 오후 4 28 37" src="https://user-images.githubusercontent.com/28642484/156124243-1849ace3-ba18-452d-88a2-f48797592e4b.png">

아시다싶이 브라우저마다 http로 접근하면 https로 자동 리다이렉션 시키는 경우가 있는데요~ 위의 스샷과 같은 경우도 http://XXX:9000 접속시 https:XXXX:9000으로 리다이렉션 시켜서요~

해결 방법1:  [velog](https://velog.io/@leyuri/%ED%81%AC%EB%A1%ACChrome-%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80-http-%EC%A3%BC%EC%86%8C-https-%EA%B0%95%EC%A0%9C-%EC%A0%84%ED%99%98-%EB%A6%AC%EB%8B%A4%EC%9D%B4%EB%A0%89%ED%8A%B8-%ED%95%B4%EC%A0%9C-%EB%B0%A9%EB%B2%95)

해결 방법2: 시크릿 브라우저 모드에서 접속

하면 해결되더라고요!

**Comment by leedoopal** [comment]
선생님 고마워요~~

![스크린샷 2022-03-02 오후 5 54 57](https://user-images.githubusercontent.com/39582981/156328399-fd6c685f-a97c-46ea-a505-cd2fa7023392.png)
그런데 이 에러는 cors 에러 아닌가용..?
http에서 접속했어요!

**Comment by leedoopal** [comment]
@KoEonYack 
https 에서 접속하면 아래와 같은 에러가 나와요~~

![스크린샷 2022-03-02 오후 5 59 37](https://user-images.githubusercontent.com/39582981/156329112-0b16e7e5-bbef-42f2-9c96-dc5cd2e07b15.png)

**Comment by leedoopal** [comment]
@KoEonYack 
아하 찾았어요~ 로컬서버를 9000으로 띄웠는데 기존 그대로 3000으로 띄워야하는군요~
성공했답니다! 고마워요~~

**Comment by leedoopal** [comment]
![스크린샷 2022-03-02 오후 6 12 58](https://user-images.githubusercontent.com/39582981/156331171-11cbba32-4d7b-4251-bed8-ce2175ca8800.png)
태그 조회에 성공했어요~~ 고마워요!
