### ISSUE TITLE
구글 애넬러틱스 스크립트 추가했어요~

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#3]
@Woohwahwa 

구글 애넬러틱스 스크립트 추가해서 index.html의 <head> 시작부분에 넣었어요!

npm run deploy도 눌렀답니다!

🦐 누가 방문하는지 살펴보아요!

**Comment by Woohwahwa** [comment]
멋져요!!!!!!🧞🧞
