### ISSUE TITLE
[BE] roles 요청사항

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Client#30]
![스크린샷 2022-03-02 오후 10 44 10](https://user-images.githubusercontent.com/39582981/156374263-8918b572-c0f2-4cf7-b3c2-bb45ca26a9a6.png)

못보던 사이에 roles가 한글로 바뀌었어요..! 혹시 영어로 돌려줄 수 있을까요? 
프론트에서 admin 인지 체크하는 부분이 있어서요! 👀

**Comment by leedoopal** [comment]
추가로.. 관리자 권한이 있는 유저인데 tags 조회에 실패하네요;;
분명 한시간전까지 되었던 것 같은데.. 무언가 필요한게 있을까요??

```json
{
    "status_code": 40004,
    "status": "TOKEN_400_04",
    "message": "접근할 수 없는 토큰입니다.",
    "errors": [
        "API 접근에 실패하였습니다. 권한을 확인해주세요"
    ]
}
```

**Comment by KoEonYack** [comment]
@leedoopal 

배포했어요~~!!!   🚀

**Comment by leedoopal** [comment]
와 너무 고마워요~~~~~~~
