### ISSUE TITLE
[BE] login cors error

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Client#31]
반가워요~~ 배포는 잘 되었나요~?

```
Access to fetch at 'http://{주소}:9000/admin/v1/login' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

오늘 로그인을 하려니 갑자기 안되네요..!
혹시 이유를 알고 있을까요?
이유를 알 수 없어요,,

**Comment by KoEonYack** [comment]
@leedoopal 

선생님 반가워요~~~~~~~~~~~

배포는 월욜에 하기로했어요...!

선생님이 로켓 개발해야하는데 자꾸 와르르 부분이 있어서 슬퍼요 ㅜㅜ

![스크린샷 2022-03-03 오후 11 09 09](https://user-images.githubusercontent.com/28642484/156580945-97970a05-3f27-4d42-805b-fcc9bf925946.png)

저는 요렇게 나와요....!

**Comment by KoEonYack** [comment]
선생님 인증쪽 로직을 바꾸었나요?!

![스크린샷 2022-03-03 오후 11 15 21](https://user-images.githubusercontent.com/28642484/156582045-3d252c3b-7db2-4a2b-9e53-0b878067833e.png)

Postman에서 http://{URL}:9000/admin/v1/login 로 호출하면 위처럼 잘 나와서요~

**Comment by leedoopal** [comment]
@KoEonYack 
인증쪽은 완전 그대로구용! 흠.... 한번 해볼게요!

**Comment by leedoopal** [comment]
@KoEonYack 
오 찾아봤는데.. 시간이 좀 걸릴 것 같아요~! 좀 더 해볼게요!

**Comment by KoEonYack** [comment]
@leedoopal 

도움이 필요한 일이 있다면 도와줄께요~~!! 👍👍

**Comment by leedoopal** [comment]
@KoEonYack 
프론트에서 가능한 방법으로 해결해보았어요~!
하지만 이게 좋은 방법인지는 생각이 필요할 것 같아요..!
우선 다른 개발을 하러 슥슥 가볼게요~~
