### ISSUE TITLE
[BE] STATUS_CODE 요청사항

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Client#32]
즐거운 주말이에요~!
호다닥 일요일이 되었네요..! 🌤️ 

작업을 하다보니 status_code가 서로 다른 부분이 있는 것 같아서 통일 시키면 어떨까..
하는 마음이 들어 이슈를 남겨요!

예 - signUp
```
status_code: 20001
```

예 - 이벤트 생성
```
status_code: 20101
```

둘다 201 같은데 코드가 달라서.. 왜 다른지 궁금해요~~~
모두 같으면 작업하기 좋을 것 같아요~~

급하지 않아서 천천히 대답 해주어도 되어요!

**Comment by KoEonYack** [comment]
@leedoopal 

반가워요~~~~~~ 로켓 월요일이 왔어요~! 🤩

그렇군요 😅.

signUp
```
status_code: 20001 -> 20101
```

20101로 응답하는게 맞아요~... Post 이니깐요..!

StatusCode 3자리 201 Create, 내부 기능별 응답값 순번 두 자리로 이루어져있어요!

201로 바꾸는게 좋을까요~?! 20101처럼 {HTTP 상태코드}{응답 순번} 5글자로 구분하는게 좋을까요~!?

편한것을 선택해보아요~~!

**Comment by leedoopal** [comment]
@KoEonYack 
이제 주말이 얼마 안남았군요..! 저는 잘보내고있답니다!!
선생님도 남은 주말 푹쉬어요~!

저는 세자리가 편하답니다 하하핫 머쓱하군요~~~

**Comment by KoEonYack** [comment]
@leedoopal 


이제 쿨쿨 잘 시간이 되었어요~~~~!!!



성공할경우 HTTP 응답값도 201이고, response body에 201이 가게되는거라 별로일것이라고 예상했는데 세자리가 편했군요~~~~

머쓱하게 제거해버릴께요~! 

API 실패했을때도 (ex. 50001 -> 500) 응답값을 HTTP 응답값 세 자리로 바꾸면 되는 것을까요?!

**Comment by leedoopal** [comment]
@KoEonYack 
앗 맞아요~ 잘시간이에요~~~
네네 400, 401, 403, 500 등등 이렇게 주면 고마울 것 같아요!
하지만 진짜 천천히 바꾸어두 된답니다..!!

**Comment by KoEonYack** [comment]
@leedoopal 

죻아요~ 변경건 배포하면 요기에다가 코멘트 달께요~!!

**Comment by leedoopal** [comment]
@KoEonYack 
대왕 고마워요!!!!!!! 좋은 밤 보내요!!!!

**Comment by KoEonYack** [comment]
@leedoopal 잘 지내구있나요~?! ☁️☁️

![스크린샷 2022-03-26 오후 2 27 34](https://user-images.githubusercontent.com/28642484/160226141-d9f309fc-5700-4118-857c-5361638783c0.png)

값을 변경해보았어요~~!! 
모든 API status_code는 세 자리 HTTP 상태코드로 응답해요!

**Comment by leedoopal** [comment]
@KoEonYack 
오 고마워요!! 참고해서 수정할게요!
