### ISSUE TITLE
[FE] 로그인 토큰 불가

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#33]
@leedoopal 

반가워요~~~~~~~!!! 

--------------------

![스크린샷 2022-03-08 오후 11 01 33](https://user-images.githubusercontent.com/28642484/157252793-61136f46-6b8b-46c5-95a0-a7fc1a2bdc6b.png)

선생님이 엄쳥 많이 작업한거 보러가려고 로컬에서 돌렸는데요!

선생님이 이전에 겪었던 상황이 나왔어요....!🥺

선생님은 어떻게 해결하셨나요~~?!

**Comment by leedoopal** [comment]
@KoEonYack 
혹시 풀 다 받았나요~~??
다 받았다면 아래처럼 해보아요~!

```
// .env.local
NEXT_PUBLIC_ADMIN_DOMAIN=http://{주소}:9000
NEXT_PUBLIC_ADMIN_URL=http://localhost:3000/admin/v1
```

**Comment by KoEonYack** [comment]
@leedoopal 

해결했어요~~! 고마워요~~!!
