### ISSUE TITLE
[BE] password 변경 관련 질문

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Client#37]
선생님 반가워요~~~~

비밀번호 변경을 만드는 중에 궁금한 점이 있어 이슈 남겨요!

비밀번호 변경 > ui가 현재 패스워드와 새로운 패스워드를 입력받는 구조인데..
![스크린샷 2022-04-14 오후 10 59 20](https://user-images.githubusercontent.com/39582981/163406576-0a7c0b06-fb82-417a-a1c3-c3321ec20db9.png)

모델을 보니 패스워드를 하나만 받아요..! (아마 새로운 패스워드 같아요)
![스크린샷 2022-04-14 오후 10 59 38](https://user-images.githubusercontent.com/39582981/163406720-0dbf274a-b230-4f40-8ced-28b2f1d4a0b5.png)

현재 패스워드 input field에서 value가 현재 패스워드가 맞는지 어떻게 알 수 있나요??

**Comment by KoEonYack** [comment]
@leedoopal 

헠;;;;; 맞아요 ㅠ old_password, new_password 이렇게 필드 두개 만들어서 보내도록 해야겠어요~ 

🥲

**Comment by KoEonYack** [comment]
배포 완료하면 여기에 코멘트 남길께요~

**Comment by KoEonYack** [comment]
@leedoopal 

선생님 배포를 해보았어요~~!

<img width="491" alt="스크린샷 2022-04-16 오전 10 52 33" src="https://user-images.githubusercontent.com/28642484/163657170-e149bd8c-f0c3-4b64-a325-a7280ead1d7b.png">

> 현재 비밀번호 일치하지 않은 경우 


<img width="481" alt="스크린샷 2022-04-16 오전 10 52 56" src="https://user-images.githubusercontent.com/28642484/163657178-59a2521f-9835-4995-b08f-0949ef4e152f.png">

> 현재 비밀번호 일치하는 경우

**Comment by leedoopal** [comment]
@KoEonYack 
와 고마워요~~

![스크린샷 2022-04-19 오후 11 14 47](https://user-images.githubusercontent.com/39582981/164024410-b1b7a8ac-93c8-407e-9ecd-67aff4058fc5.png)
그런데 혹시.. 패스워드 변경 관리자만 가능한가요? 그럼 일반 사용자는 패스워드를 바꾸지 못하나요..?

**Comment by leedoopal** [comment]
@KoEonYack 
admin 계정은 변경이 잘되는데, cindy 계정은 패스워드 바꾸려니 에러가 나네요..;;
![스크린샷 2022-04-19 오후 11 21 01](https://user-images.githubusercontent.com/39582981/164026211-20b99b52-92e1-436a-8ad6-455eb7f64367.png)

authType admin 이라는데 알 수 없어요,,,,

**Comment by KoEonYack** [comment]
@leedoopal 헉 살펴볼께요 ㅠ

**Comment by leedoopal** [comment]
@KoEonYack 
ㅠㅠ고마워요

**Comment by KoEonYack** [comment]
@leedoopal 씬디 현재 비밀번호가 무엇인가요...?! 디비는 암호화되어서 평문을 볼수없어요~!

**Comment by leedoopal** [comment]
@KoEonYack cindy123 이에요!

**Comment by KoEonYack** [comment]
![스크린샷 2022-04-19 오후 11 29 26](https://user-images.githubusercontent.com/28642484/164027620-2117c472-5b7c-4866-915a-09e6b72474a3.png)
아~ 선생님 AuthType이 ADMIN이고 Role이 비어있어서 구래요!

AuthType이 무엇이냐면요!
https://github.com/brave-people/Dev-Event-Client/issues/35 여기에서 남겼던것처럼

![스크린샷 2022-04-19 오후 11 30 29](https://user-images.githubusercontent.com/28642484/164027876-b6b748ad-a8aa-4bf7-9136-cb834b9d4693.png)

요런 것이에요!

쇼셜 가입이 생기면서 이메일이 중복해서 아이디에 들어올 수가 있게 되었어요! 그래서 아이디 + AuthType(네이버, 카카오, 구글, 깃허브) 이렇게 고유 회원을 식별하게 되었어요!

AuthType ADMIN이면 관리자 계정이라는 의미에요!

API  접근 권한은 JWT 토큰의 roles 값을 보고 판단해요! 

![스크린샷 2022-04-19 오후 11 32 31](https://user-images.githubusercontent.com/28642484/164028323-a81d8c0a-3676-443d-8d55-c722c75ba43c.png)

admin 계정의 JWT인데요~ ROLE에 ADMIN이 있어서 비밀번호 변경이 가능했던거에요~

회원에게 권한 부여는 [POST] `/admin/v1/users/role`  이 API를 사용하면 됩니다!

cindy계정에게 ROLE_ADMIN 혹은 ROLE_MANAGER 권한을 주면 비밀번호를 바꿀 수 있어요~

**Comment by leedoopal** [comment]
@KoEonYack 
에구 그랬군요;;; 이번주 벌써 정신이 혼미하네요,,,,
알려주어서 고마워요!!!

**Comment by KoEonYack** [comment]
@leedoopal 

힘을 내어요~~ ㅜㅜ 💊 

고마워요~~~~~~~!!
