### ISSUE TITLE
[FE] netlify 사용으로 인한 cors 에러

### ISSUE THREAD

**Issue by leedoopal** [brave-people/Dev-Event-Client#39]
툴을 github-pages 에서 netlify로 갈아탔답니다 🥸

#### 1) 사연
github pages + nextjs 에서는 next export를 명령어를 통한 out directory 산출이 필수인데,
`next export` + 사용중인 nextjs [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props)(getServerSideProps 간단 요약: 없이 살기 힘듬) 빌드에 실패하여 살펴보니..

`next export` 시 static 파일을 만들게되지만, getServierSideProps는 변하는 값이기 때문에 이렇게 빌드를 할 수 없다네요.
참고: [https://nextjs.org/docs/messages/gssp-export](https://nextjs.org/docs/messages/gssp-export)

#### 2) 한 줄 요약
nextjs data fetching을 위해 getServierSideProps 필요 <-> next export 불가능 <-> output 없음 <-> github pages 빌드 불가

#### 3) 문의
이렇게 엮이고 엮이는 관계 끝에 netlify로 갈아타게 되었어요

![스크린샷 2022-05-14 오전 2 01 56](https://user-images.githubusercontent.com/39582981/168332940-62cee7e9-f4da-4403-97a8-1a6f2e1f258c.png)
그래서 cors 에러가 발생하게되는데 요거 혹시 백에서 처리 가능할까요????

---
#### 변경 된 dev event client domain
- [https://brave-people-dev-event.netlify.app](https://brave-people-dev-event.netlify.app)

**Comment by KoEonYack** [comment]
@leedoopal 

그렇군요~~! Starter 플랜으로 문제가 없을까요~?!

CORS는 host 화이트리스트 추가하고 알려드릴께요!

**Comment by KoEonYack** [comment]
@leedoopal 

CORS 이슈 해결하여서 정상 로그인되어요~ 

<img width="1118" alt="스크린샷 2022-05-14 오후 5 06 35" src="https://user-images.githubusercontent.com/28642484/168416988-b6354a6a-c96d-4610-8217-352c4cd13d35.png">

favicon 500 error 나오는데~

![image](https://user-images.githubusercontent.com/28642484/168417004-4a91936d-4103-4c63-998b-13334ece3934.png)

이거 사용해보아요!

**Comment by leedoopal** [comment]
@KoEonYack 
ㅋㅋㅋㅋㅋㅋ파비콘 고마워요!!
starter plan github pages랑 비교해봤을 때 저는 다 괜찮은 것 같아요! 
고마워요~~~~~~~!!
