### ISSUE TITLE
웨일 확장앱 개발시 질문들..

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#4]
@Woohwahwa 
안녕하세요~ WooHWA~

```html 
<body style="width:100%; overflow-x:hidden;  overflow-y:hidden;">
<iframe 
    width="100%" height="100%" 
    src="https://brave-people.github.io/Dev-Event-Client/" 
    name="test" id="dev-event" 
    scrolling="yes" 
    align="center">
</iframe>
</body>
```

위와 같이 iframe을 넣었는데 혹시 수정할 부분이 있을까요?

그리고, iframe은 구글 애넬러틱스에 안잡히는게 맞죠?!?!

**Comment by KoEonYack** [comment]
![image](https://user-images.githubusercontent.com/28642484/101978760-b557ea80-3c9a-11eb-833b-8ff9483ffca3.png)

일단 웨일 스토어 심사에 올렸어요~~

**Comment by Woohwahwa** [comment]
iframe은 따로 수정할게 없을 것 같아용! 
그리고 ga에 안잡히긴 한데 따로 설정값을 바꿔주면 가능해요! 혹시 필요한가용???

**Comment by KoEonYack** [comment]
얼마나 사용할지 모르겠지만 확장앱도 통계에 잡히면 좋겠어요~~

**Comment by Woohwahwa** [comment]
@KoEonYack ga 권한 저한테도 줄 수 있을까용??

**Comment by KoEonYack** [comment]
@Woohwahwa 
https://marketingbr.tistory.com/99 <- 요로케 권한주는곤가요?
Google 계정을 알려주세요~

**Comment by Woohwahwa** [comment]
아 맞아요!!! 계정은 1233wsh@gmail.com 이에요!! 제가 설정값을 iframe도 될 수 있게 해놓을게요

**Comment by KoEonYack** [comment]
@Woohwahwa 
권한 주었어요~~
