### ISSUE TITLE
Dev event 웨일 확장앱출시!

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#5]
@Woohwahwa 

https://store.whale.naver.com/detail/peoakdpkgaaddnccepdmgnjghelkdein

확장앱 출시되었어용용용용ㅇ용ㅇ용!!!!!!!!!!!!

**Comment by KoEonYack** [comment]
@Woohwahwa 

![image](https://user-images.githubusercontent.com/28642484/102215169-b13aff80-3f1c-11eb-96c2-bf1fa555640c.png)

홍보 36시간이 지난 현재 방문자수! 
직접 링크 형식으로 제공안했는데 예상보다 높네용!! 
이제 에드센스 달 준비해도 될것가타용

**Comment by Woohwahwa** [comment]
조아용!!!

**Comment by KoEonYack** [comment]
@Woohwahwa 
쌤이 멋있게 만들어서 사람들이 구경오나바여!!! 고마워요!! 대단해요!!! 
이슈는 닫을꼐용 슉
