### ISSUE TITLE
[💡 개선 아이디어] CSS 적용

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#55]
@leedoopal 

반가워요~

--------
## 1. 삭제 안내 CSS 적용

<img width="199" alt="스크린샷 2022-07-14 오후 6 51 00" src="https://user-images.githubusercontent.com/28642484/178955282-25cdb9cf-1e9e-449b-a036-834101d375d1.png">

- 삭제 안내 CSS가 적용이 되지 않았어요~

--------

## 2. 태그 ~ 시작일시 CSS 수정

<img width="705" alt="스크린샷 2022-07-14 오후 6 52 00" src="https://user-images.githubusercontent.com/28642484/178955457-33a05354-9fb1-4a1d-965f-ee4764b8f9a9.png">

- 시간 표시 체크박스가 시작일시, 종료일시 모두 적용되었어요! 대단해요~~
- 시간 표시 체크박스가 이동하면서 태그 추가했을때 시작일시에 곂쳐서 보여요!

--------

## 3. 시간 음영 
<img width="383" alt="스크린샷 2022-07-14 오후 6 54 00" src="https://user-images.githubusercontent.com/28642484/178955865-c62545cd-673c-4ce7-a0cf-e15c0a4195bb.png">

- 시간 표시에 체크가 되지 않았으면 쬐끔 어두운 색으로 시간 input 박스로 보여지면 어떨까 생각이 들어요~~
--------

이상이에요~~

**Comment by leedoopal** [comment]
오 의견 고마워요~~~~~~~~
적용하고 말해줄게요!!

**Comment by leedoopal** [comment]
@KoEonYack 
오 저두요~~~~~~!!
아이디어가 있다면 이슈 등록 많이 해주어요~~~~
