### ISSUE TITLE
[🐞 Bug] 개발자 행사 수정 -> 태그 클릭시 메인 페이지로 이동

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#58]
@leedoopal 

반가워요~~~ 늦은 밤인데 알람이 간다면 미안해용 !

-----------
![스크린샷 2022-07-19 오후 11 42 25](https://user-images.githubusercontent.com/28642484/179778652-6b961e2a-7649-45a3-a17a-305fe9482056.png)

> 개발자 행사 수정 -> 태그 아무거나 클릭시 메인 페이지로 이동

(개발자 행사 생성에서 태그를 클릭하면 태그가 사라지는 디테일에 놀랐어요!!)

**Comment by leedoopal** [comment]
@KoEonYack 
오 늦은 밤까지 개선 아이디어를 남겨주었군요ㅠㅠ 고마워요!
아무 태그나 클릭하면 메인페이지로 이동시키자는 의견인가요??

**Comment by KoEonYack** [comment]
@leedoopal 

아뇨~~~ 

개발자 행사 생성과 다르게 수정에서는 태그 클릭시 태그가 제거되어야 하는데 메인 페이지로 이동한다는 말이었어요!!

**Comment by leedoopal** [comment]
@KoEonYack 
아하~~~~ 고마워요!!

**Comment by KoEonYack** [comment]
@leedoopal 와 벌써 소원수리 커밋을 했어요~~~~~ 혹시 로켓인가요? 
고마워요!!!!

**Comment by leedoopal** [comment]
@KoEonYack 
엄청난 칭찬이에요~~~~~~ 힘이나네여 고마워요~~~~~~
