### ISSUE TITLE
[💡 개선 아이디어] 태그 색상 직접입력

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#74]
@leedoopal 

선생님 반가워요~~~ 홍수에 안 떠내려갔을까요~~~~~~~~~~~~~~?!

---------------------------

![스크린샷 2022-08-09 오후 10 00 29](https://user-images.githubusercontent.com/28642484/183653164-0daecad2-f2bc-4d3c-89ef-888a6998d738.png)

![스크린샷 2022-08-09 오후 10 00 45](https://user-images.githubusercontent.com/28642484/183653207-4b79b6a6-7b2a-425e-89e4-5c09071b417c.png)

태그 갯수가 많아서 이미 등록된 색상 수로는 부족하더라고요!

![스크린샷 2022-08-09 오후 10 01 30](https://user-images.githubusercontent.com/28642484/183653332-6409edc4-e880-4c0e-bd7e-c52b7f47b733.png)
이전에 제가 제안했던것처럼 직접 입력도 있으면 좋지 않을까 제안을 해보아요!

> 제안서: https://docs.google.com/presentation/d/1eacjUtv1egzaCVHOUSKJ5B-PDYsrKZM6TWbMcB0MdIM/edit#slide=id.p

**Comment by ohh31** [comment]
안녕하세요~! 우연히 이슈를 보게 되었는데요! 

디자인할 때 태그 컬러가 많으면 통일성이 없게 느껴질 수 있어 
카테고리 별로 분류할 수 있도록 12가지 색상으로 정해뒀었어요! 
리마인드를 드렸어야했는데..! 

색상을 직접 입력하는 것도 좋은 아이디어지만 추가 개발이 필요하시니
제가 태그별로 색상을 분류해 지정해보아도 될까요~?

**Comment by leedoopal** [comment]
@KoEonYack 
하필 월요일 출근했다가 돌아오는 길 계곡을 만났지 뭐예요..!
개선 의견을 주어서 고마워요~~~~~

---
@KoEonYack @ohh31
세원친구 말처럼 정해진 색 안에서 고르는게 좀 더 나을 것 같아용
색상 직접입력 또는 color picker 를 넣으면 제 개인적인 재미요소가 될 수는 있겠지만..
서비스적으로 불필요하지 않을까 싶어요,,  

저는 4개 내지 8개 정도도 좋은 것 같아요!

**Comment by KoEonYack** [comment]
@ohh31 

색상을 고정하였구나~~~!! 알려주어서 감사해!!


-------------

@leedoopal 

물에 안떠내려갔군요!!
선생님 의견 고마워요~~~~~

**Comment by KoEonYack** [comment]
이슈 닫습니다!!
