### ISSUE TITLE
favicon 변경

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#8]
@Woohwahwa 

![image](https://user-images.githubusercontent.com/28642484/103349321-eda35980-4adf-11eb-8a07-1a25c1bed591.png)

![image](https://user-images.githubusercontent.com/28642484/103349347-fb58df00-4adf-11eb-9b72-31445d2bcf86.png)

웨일 확장앱에서 사용하고있는  [D] 로고로 바꾸었어요!

**Comment by Woohwahwa** [comment]
로고가 더 예뻐졌어요!!🤭  ㅠㅠㅠㅠ 늦게봐서 미안해요ㅠㅠ
저는 그동안 캘린더 버그와 모바일에서 상단 메뉴가 가려지는 버그들을 고치고 있었어요 배포 끝났답니당!

**Comment by KoEonYack** [comment]
@Woohwahwa 대단해요!!!!!
