### ISSUE TITLE
[💡 개선 아이디어] 테그 선택시 자동 추가

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#83]
CC. @osj3474 , @ohh31  (이젠 제안의 경우 모두를 추가해요!)

----------

@leedoopal 

선생님 반가워요~~~~~

![스크린샷 2022-09-01 오후 10 34 57](https://user-images.githubusercontent.com/28642484/187927186-b95861a2-d44d-4e73-907f-c8633c303379.png)

이전에는 테그 마우스로 클릭했을때 태그 input 폼에 자동으로 추가되었는데요~ 이제는 그렇지 않아요.....!

혹시 태그 목록에서 태그 항목을 클릭했을때 input 폼에 자동으로 추가해주는것은 어떤가요~!?

**Comment by KoEonYack** [comment]
@leedoopal 

![화면 기록 2022-09-06 오후 11 30 05](https://user-images.githubusercontent.com/28642484/188662339-74ac7337-0108-4885-aa5e-00c9add137d5.gif)

카톡으로 보낸 GIF 여기에도 첨부할께요~~~~!!! 고마워요!!

**Comment by leedoopal** [comment]
@KoEonYack 선생님 수정해서 dev, prod 모두 배포 완료되었어요~!
지난번 제 맥북에서 재현이 되길래 수정했는데, 되는지 한번 확인부탁해요~~~~!!

**Comment by KoEonYack** [comment]
@leedoopal 

오 선생님~~~ 해결되었어요~~~~

timeout을 늘렸군요~~~~! 대단해요!!!!!
