### ISSUE TITLE
[🐞 bug] 회원정보 수정시 정보 변경되지 않음

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#84]
@leedoopal 

선생님 반가워요~~~~~

(저는 오늘은 회사 창립기념일이여서 휴일이랍니다 >ㅁ<)

----------------------------------------

<img width="1089" alt="스크린샷 2022-09-05 오후 2 20 30" src="https://user-images.githubusercontent.com/28642484/188365977-8264017c-33ed-4908-8f90-7750eb989ecd.png">

회원정보 수정에서 이름을 변경했는데요~

권한 부여에 성공했다고 나오네용!

PUT ​/admin​/v1​/users

위의 API 이용하면 이름이랑 이메일을 수정할 수 있어요~~

**Comment by KoEonYack** [comment]
@leedoopal 오 선생님~~~~~~~ 소원을 로켓으로 들어주군요~~~~~!!!

**Comment by leedoopal** [comment]
@KoEonYack 앗 그렇긴한데..! 수정하고나니 버그가 좀 보이더라구요.
수정하고 다시 알려줄게요!!

**Comment by KoEonYack** [comment]
@leedoopal 

API 로직이 최신화가 안되어서요...!

수정 대상(현재 로그인한 사용자) 아이디가 같은 사람이면 정보가 동시에 Update가 될꺼에요...!

상진군이 아이디를 회원번호 기준으로 조회 하도록 API를 최신화 할 예정이랍니다!

(cc. @osj3474 )

**Comment by leedoopal** [comment]
@KoEonYack 와 로켓답변 고마워요~~~~

**Comment by KoEonYack** [comment]
@leedoopal 

수정건 prod, dev 배포했어요~~~!!

**Comment by leedoopal** [comment]
@KoEonYack 
오 고마워요 확인했어요~!!

**Comment by KoEonYack** [comment]
@leedoopal 

고마워요~~~~!!! 이슈는 닫을께요!!
