### ISSUE TITLE
새로운 페이지 제작관련 제안사항~

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#9]
@leedoopal 안녕하세요~ 잘 지내시나요!

다름이 아니라, 개발자 행사가 끝나면 일부 행사는 다시 볼 수 있는 링크를 남겨 놓아요~

지금까지 Dev Event처럼 행사를 알려주는 서비스는 여럿 있으나 다시 볼 수 있는 서비스를 별도로 모아놓은 곳은 없어요,,

Dev Event는 새로운 행사를 인간 크롤러가 직접 찾아서 수기로 업데이트 수체 초콜릿 서비스이기때문에 

어떤 시점까지 가면 지속할 수 없을것이라는 생각이 들어요~ (지금은 인간크롤러 성능이 좋아서 많은 스타를 받고 있지만요,,,!)

하지만 VOD로 과거 행사를 다시볼 수 있는 하나의 서비스로 남는다면 사람들이 계속해서 doopal이 만든 서비스를 이용해 줄꺼라고 생각이 들어요!

개발자 모임, 개발자 동아리는 구현은 미루어져도 좋지만 VOD를 어떻게 아룸답게 보여주면 좋을지 고민해 보면 좋을것 같아요!!

이건 저의 생각이여서, , , !! 언제든지 틀릴 수 있지만 VOD 페이지 제작에 대해서 의견을 내 보아요~~~

**Comment by leedoopal** [comment]
고민해보고 공유할게여!! 안그래도 이것부터 하려고 했었는데 고마워여!!!

**Comment by KoEonYack** [comment]
@leedoopal 확인 고마워요~~ 이슈는 닫을께요~!
