### ISSUE TITLE
[💡 개선 아이디어] 브라우저 종료시 아이디 삭제

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Client#96]
@leedoopal  (cc. @ohh31, @ohh31)

선생님 반가워요~

오랜만에 제안을 들고왔어요! (사실 전에 말한 제안이였지만.. issue로 등록해볼께요)

----------------------------------------------------------------------

<img width="467" alt="스크린샷 2022-10-01 오후 5 01 40" src="https://user-images.githubusercontent.com/28642484/193399566-6e0484cf-3cc0-4ffc-a1a8-5acc0577eac2.png">

아이디 저장하기 누르고, 브라우저 종료시 이전에 저장된 아이디가 삭제되어있어요!

<img width="549" alt="image" src="https://user-images.githubusercontent.com/28642484/193399769-5bda049f-414d-4d8b-89cf-c847fab907d1.png">

쿠키 확장앱으로 해당 값을 봤을때 세션 쿠키여서 그런것 같은데....! 확인 가능할까요~~~?!

Test env: Edge, Safari

**Comment by leedoopal** [comment]
<img width="176" alt="스크린샷 2022-10-02 오후 9 09 45" src="https://user-images.githubusercontent.com/39582981/193453223-bbee75c3-3f5b-4fbb-9c7a-676866d34163.png">
@KoEonYack 수정해서 dev, prod 배포되었어요~~!

**Comment by KoEonYack** [comment]
@leedoopal 

와!! 빨라요~~~~~~~! 고마워요!!

**Comment by leedoopal** [comment]
@KoEonYack 와 로켓확인 고마워요~~~~~~ 🚀
